In [25]:
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.model_selection import train_test_split

In [26]:
model = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=1)
X, y = np.arange(10).reshape((5, 2)), range(5)
print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [15]:
y_train

[2, 0, 3]

In [16]:
X_test

array([[2, 3],
       [8, 9]])

In [17]:
y_test

[1, 4]

In [30]:
#Supervisado
model.fit(X_train, y_train) #Supervisado
model.predict(X_test) #Supervisado

array([1., 4.])