# Ejercicios NumPy

Esta serie de ejercicios tienen como objetivo que comprueben los conocimientos adquiridos. Inicial con ejercicios simples y se se complican gradualmente.

#### Importación de NumPy 

In [1]:
import numpy as np

#### Crear un arreglo de 5 ceros  

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### Crear un arreglo de 10 unos

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un arreglo de 5  cincos 

In [4]:
5 * np.ones(5)

array([5., 5., 5., 5., 5.])

#### Crear un arreglo de números consecutivos empezando en 10 terminando en 30  

In [5]:
np.arange(10, 31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

#### Crear un arreglo de todos los  números pares  empezando en 10 terminando en 30  

In [6]:
np.arange(10, 31, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

#### Crear  un matriz  de 3x3  formada por números consecutivos del 0 al 8 

In [7]:
np.matrix("0 1 2; 3 4 5; 6 7 8")

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### Crear una matriz identidad  de 5x5

In [9]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Crear un número aleatorio entre 0 y 10

In [14]:
np.random.uniform(0, 10)

8.01175712307416

#### Generen un arreglo de 20 elementos aleatorios  usando una distribución normal estándar 

In [16]:
np.random.rand(1, 20)

array([[0.27683025, 0.38930976, 0.90956075, 0.73521557, 0.02312717,
        0.74319076, 0.61291521, 0.27413055, 0.67849795, 0.26700633,
        0.9275607 , 0.31034496, 0.62104192, 0.51367123, 0.22429524,
        0.04267423, 0.61915605, 0.78568297, 0.84857699, 0.62460824]])

#### Crear la siguiente matriz 

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [17]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crear un arreglo de 20 elementos equidistantes entre los valores de 0 a 1 

In [18]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexación en arreglos numpy 

En esta sección se evaluará su conocimiento para obtener pociones de la matriz generada, para replicarlo tienen que usar exclusivamente  indexación 

In [44]:
mat = np.arange(1, 26).reshape(5, 5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Extraer la siguiente matriz: 
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [45]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Extraer la siguiente celda:  15

In [46]:
mat[2,-1]

15

Extraer la siguiente matriz: 
    array([[ 2],
       [ 7],
       [12]])

In [47]:
mat[0:-2, 1:2]

array([[ 2],
       [ 7],
       [12]])

Extraer la siguiente matriz:  array([21, 22, 23, 24, 25])

In [48]:
mat[-1]

array([21, 22, 23, 24, 25])

Extraer la siguiente matriz: 
    array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Operaciones adiciones 

No todo puede ser cubierto por el curso sin embargo existen funciones para hacerlo [funciones universales](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)


Obtener la suma de todos los valores en la matriz **mat**

In [50]:
np.sum(mat)

325

Obtener la desviación estándar de la matriz **mat**

In [51]:
np.std(mat)

7.211102550927978

Obtener la suma de cada una de las columnas en  la matriz **mat**

In [53]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

# Buen trabajo 

In [43]:
# Excelente curso!